question_data = [{"type": "boolean", "difficulty": "medium", "category": "Sports",
                  "question": "Formula E is an auto racing series that uses hybrid electric race cars.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "easy",
                  "category": "Entertainment: Board Games",
                  "question": "Snakes and Ladders was originally created in India?",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "medium", "category": "Politics",
                  "question": "George W. Bush lost the popular vote in the 2004 United States presidential election.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "medium",
                  "category": "Entertainment: Japanese Anime &amp; Manga",
                  "question": "In JoJo\'s Bizarre Adventure\'s;, Father Enrico Pucchi uses a total of 3 stands in Part 6: Stone Ocean.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "medium",
                  "category": "Science: Computers",
                  "question": "The HTML5 standard was published in 2014.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "medium",
                  "category": "Science Nature",
                  "question": "Scientists accidentally killed the once known world\'s oldest living creature, a mollusc, known to be aged as 507 years old.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "medium",
                  "category": "Entertainment: Film",
                  "question": "The original ending of \"Little Shop Of Horrors\" has the plants taking over the world.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "easy", "category": "Animals",
                  "question": "A bear does NOT defecate during hibernation. ",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "easy",
                  "category": "Entertainment: Video Games",
                  "question": "The ultimate phrase used by Pharah from Overwatch is: \"Justice rains from above!\"",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "easy",
                  "category": "Science Nature",
                  "question": "Water always boils at 100degC, 212F, 373.15K, no matter where you are.",
                  "correct_answer": "False", "incorrect_answers": ["True"]}]
